filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/app.log
    fields:
      service: hermes_logs

  - type: log
    enabled: true
    paths:
      - /app/logs/app.metric
    fields:
      service: hermes_metrics

output.logstash:
  # При запуске вне докера вместо athena-logstash нужно указать правильный адрес хоста.
  hosts: ["athena-logstash:5044"]