#
# Build stage
#
FROM maven:3.9.9-eclipse-temurin-21 AS build

COPY src /home/app/src
COPY pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM eclipse-temurin:21

COPY --from=build /home/app/target/common-alpha.jar /common/common-alpha.jar
