// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hermes.proto

package com.pantheon.hermes.grpc;

public final class HermesOuterClass {
  private HermesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GraphOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Graph)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    java.util.List<com.pantheon.hermes.grpc.HermesOuterClass.Edge> 
        getEdgeList();
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    com.pantheon.hermes.grpc.HermesOuterClass.Edge getEdge(int index);
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    int getEdgeCount();
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    java.util.List<? extends com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder> 
        getEdgeOrBuilderList();
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder getEdgeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Graph}
   */
  public  static final class Graph extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Graph)
      GraphOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Graph.newBuilder() to construct.
    private Graph(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Graph() {
      edge_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Graph(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                edge_ = new java.util.ArrayList<com.pantheon.hermes.grpc.HermesOuterClass.Edge>();
                mutable_bitField0_ |= 0x00000001;
              }
              edge_.add(
                  input.readMessage(com.pantheon.hermes.grpc.HermesOuterClass.Edge.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          edge_ = java.util.Collections.unmodifiableList(edge_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Graph_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Graph_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pantheon.hermes.grpc.HermesOuterClass.Graph.class, com.pantheon.hermes.grpc.HermesOuterClass.Graph.Builder.class);
    }

    public static final int EDGE_FIELD_NUMBER = 1;
    private java.util.List<com.pantheon.hermes.grpc.HermesOuterClass.Edge> edge_;
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    public java.util.List<com.pantheon.hermes.grpc.HermesOuterClass.Edge> getEdgeList() {
      return edge_;
    }
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    public java.util.List<? extends com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder> 
        getEdgeOrBuilderList() {
      return edge_;
    }
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    public int getEdgeCount() {
      return edge_.size();
    }
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    public com.pantheon.hermes.grpc.HermesOuterClass.Edge getEdge(int index) {
      return edge_.get(index);
    }
    /**
     * <code>repeated .Edge edge = 1;</code>
     */
    public com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder getEdgeOrBuilder(
        int index) {
      return edge_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < edge_.size(); i++) {
        output.writeMessage(1, edge_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < edge_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, edge_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pantheon.hermes.grpc.HermesOuterClass.Graph)) {
        return super.equals(obj);
      }
      com.pantheon.hermes.grpc.HermesOuterClass.Graph other = (com.pantheon.hermes.grpc.HermesOuterClass.Graph) obj;

      boolean result = true;
      result = result && getEdgeList()
          .equals(other.getEdgeList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEdgeCount() > 0) {
        hash = (37 * hash) + EDGE_FIELD_NUMBER;
        hash = (53 * hash) + getEdgeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pantheon.hermes.grpc.HermesOuterClass.Graph prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Graph}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Graph)
        com.pantheon.hermes.grpc.HermesOuterClass.GraphOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Graph_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Graph_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pantheon.hermes.grpc.HermesOuterClass.Graph.class, com.pantheon.hermes.grpc.HermesOuterClass.Graph.Builder.class);
      }

      // Construct using com.pantheon.hermes.grpc.HermesOuterClass.Graph.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEdgeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (edgeBuilder_ == null) {
          edge_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          edgeBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Graph_descriptor;
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Graph getDefaultInstanceForType() {
        return com.pantheon.hermes.grpc.HermesOuterClass.Graph.getDefaultInstance();
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Graph build() {
        com.pantheon.hermes.grpc.HermesOuterClass.Graph result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Graph buildPartial() {
        com.pantheon.hermes.grpc.HermesOuterClass.Graph result = new com.pantheon.hermes.grpc.HermesOuterClass.Graph(this);
        int from_bitField0_ = bitField0_;
        if (edgeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            edge_ = java.util.Collections.unmodifiableList(edge_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.edge_ = edge_;
        } else {
          result.edge_ = edgeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pantheon.hermes.grpc.HermesOuterClass.Graph) {
          return mergeFrom((com.pantheon.hermes.grpc.HermesOuterClass.Graph)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pantheon.hermes.grpc.HermesOuterClass.Graph other) {
        if (other == com.pantheon.hermes.grpc.HermesOuterClass.Graph.getDefaultInstance()) return this;
        if (edgeBuilder_ == null) {
          if (!other.edge_.isEmpty()) {
            if (edge_.isEmpty()) {
              edge_ = other.edge_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEdgeIsMutable();
              edge_.addAll(other.edge_);
            }
            onChanged();
          }
        } else {
          if (!other.edge_.isEmpty()) {
            if (edgeBuilder_.isEmpty()) {
              edgeBuilder_.dispose();
              edgeBuilder_ = null;
              edge_ = other.edge_;
              bitField0_ = (bitField0_ & ~0x00000001);
              edgeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEdgeFieldBuilder() : null;
            } else {
              edgeBuilder_.addAllMessages(other.edge_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pantheon.hermes.grpc.HermesOuterClass.Graph parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pantheon.hermes.grpc.HermesOuterClass.Graph) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.pantheon.hermes.grpc.HermesOuterClass.Edge> edge_ =
        java.util.Collections.emptyList();
      private void ensureEdgeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          edge_ = new java.util.ArrayList<com.pantheon.hermes.grpc.HermesOuterClass.Edge>(edge_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.pantheon.hermes.grpc.HermesOuterClass.Edge, com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder, com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder> edgeBuilder_;

      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public java.util.List<com.pantheon.hermes.grpc.HermesOuterClass.Edge> getEdgeList() {
        if (edgeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(edge_);
        } else {
          return edgeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public int getEdgeCount() {
        if (edgeBuilder_ == null) {
          return edge_.size();
        } else {
          return edgeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public com.pantheon.hermes.grpc.HermesOuterClass.Edge getEdge(int index) {
        if (edgeBuilder_ == null) {
          return edge_.get(index);
        } else {
          return edgeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder setEdge(
          int index, com.pantheon.hermes.grpc.HermesOuterClass.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.set(index, value);
          onChanged();
        } else {
          edgeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder setEdge(
          int index, com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.set(index, builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder addEdge(com.pantheon.hermes.grpc.HermesOuterClass.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.add(value);
          onChanged();
        } else {
          edgeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder addEdge(
          int index, com.pantheon.hermes.grpc.HermesOuterClass.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.add(index, value);
          onChanged();
        } else {
          edgeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder addEdge(
          com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.add(builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder addEdge(
          int index, com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.add(index, builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder addAllEdge(
          java.lang.Iterable<? extends com.pantheon.hermes.grpc.HermesOuterClass.Edge> values) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, edge_);
          onChanged();
        } else {
          edgeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder clearEdge() {
        if (edgeBuilder_ == null) {
          edge_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          edgeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public Builder removeEdge(int index) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.remove(index);
          onChanged();
        } else {
          edgeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder getEdgeBuilder(
          int index) {
        return getEdgeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder getEdgeOrBuilder(
          int index) {
        if (edgeBuilder_ == null) {
          return edge_.get(index);  } else {
          return edgeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public java.util.List<? extends com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder> 
           getEdgeOrBuilderList() {
        if (edgeBuilder_ != null) {
          return edgeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(edge_);
        }
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder addEdgeBuilder() {
        return getEdgeFieldBuilder().addBuilder(
            com.pantheon.hermes.grpc.HermesOuterClass.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder addEdgeBuilder(
          int index) {
        return getEdgeFieldBuilder().addBuilder(
            index, com.pantheon.hermes.grpc.HermesOuterClass.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .Edge edge = 1;</code>
       */
      public java.util.List<com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder> 
           getEdgeBuilderList() {
        return getEdgeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.pantheon.hermes.grpc.HermesOuterClass.Edge, com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder, com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder> 
          getEdgeFieldBuilder() {
        if (edgeBuilder_ == null) {
          edgeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.pantheon.hermes.grpc.HermesOuterClass.Edge, com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder, com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder>(
                  edge_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          edge_ = null;
        }
        return edgeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Graph)
    }

    // @@protoc_insertion_point(class_scope:Graph)
    private static final com.pantheon.hermes.grpc.HermesOuterClass.Graph DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pantheon.hermes.grpc.HermesOuterClass.Graph();
    }

    public static com.pantheon.hermes.grpc.HermesOuterClass.Graph getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Graph>
        PARSER = new com.google.protobuf.AbstractParser<Graph>() {
      @java.lang.Override
      public Graph parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Graph(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Graph> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Graph> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.pantheon.hermes.grpc.HermesOuterClass.Graph getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EdgeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Edge)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 vertexFrom = 1;</code>
     */
    int getVertexFrom();

    /**
     * <code>int32 vertexTo = 2;</code>
     */
    int getVertexTo();

    /**
     * <code>float summand = 3;</code>
     */
    float getSummand();

    /**
     * <code>float multiplier = 4;</code>
     */
    float getMultiplier();
  }
  /**
   * Protobuf type {@code Edge}
   */
  public  static final class Edge extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Edge)
      EdgeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Edge.newBuilder() to construct.
    private Edge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Edge() {
      vertexFrom_ = 0;
      vertexTo_ = 0;
      summand_ = 0F;
      multiplier_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Edge(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              vertexFrom_ = input.readInt32();
              break;
            }
            case 16: {

              vertexTo_ = input.readInt32();
              break;
            }
            case 29: {

              summand_ = input.readFloat();
              break;
            }
            case 37: {

              multiplier_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Edge_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Edge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pantheon.hermes.grpc.HermesOuterClass.Edge.class, com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder.class);
    }

    public static final int VERTEXFROM_FIELD_NUMBER = 1;
    private int vertexFrom_;
    /**
     * <code>int32 vertexFrom = 1;</code>
     */
    public int getVertexFrom() {
      return vertexFrom_;
    }

    public static final int VERTEXTO_FIELD_NUMBER = 2;
    private int vertexTo_;
    /**
     * <code>int32 vertexTo = 2;</code>
     */
    public int getVertexTo() {
      return vertexTo_;
    }

    public static final int SUMMAND_FIELD_NUMBER = 3;
    private float summand_;
    /**
     * <code>float summand = 3;</code>
     */
    public float getSummand() {
      return summand_;
    }

    public static final int MULTIPLIER_FIELD_NUMBER = 4;
    private float multiplier_;
    /**
     * <code>float multiplier = 4;</code>
     */
    public float getMultiplier() {
      return multiplier_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vertexFrom_ != 0) {
        output.writeInt32(1, vertexFrom_);
      }
      if (vertexTo_ != 0) {
        output.writeInt32(2, vertexTo_);
      }
      if (summand_ != 0F) {
        output.writeFloat(3, summand_);
      }
      if (multiplier_ != 0F) {
        output.writeFloat(4, multiplier_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vertexFrom_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, vertexFrom_);
      }
      if (vertexTo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, vertexTo_);
      }
      if (summand_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, summand_);
      }
      if (multiplier_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, multiplier_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pantheon.hermes.grpc.HermesOuterClass.Edge)) {
        return super.equals(obj);
      }
      com.pantheon.hermes.grpc.HermesOuterClass.Edge other = (com.pantheon.hermes.grpc.HermesOuterClass.Edge) obj;

      boolean result = true;
      result = result && (getVertexFrom()
          == other.getVertexFrom());
      result = result && (getVertexTo()
          == other.getVertexTo());
      result = result && (
          java.lang.Float.floatToIntBits(getSummand())
          == java.lang.Float.floatToIntBits(
              other.getSummand()));
      result = result && (
          java.lang.Float.floatToIntBits(getMultiplier())
          == java.lang.Float.floatToIntBits(
              other.getMultiplier()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERTEXFROM_FIELD_NUMBER;
      hash = (53 * hash) + getVertexFrom();
      hash = (37 * hash) + VERTEXTO_FIELD_NUMBER;
      hash = (53 * hash) + getVertexTo();
      hash = (37 * hash) + SUMMAND_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSummand());
      hash = (37 * hash) + MULTIPLIER_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMultiplier());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pantheon.hermes.grpc.HermesOuterClass.Edge prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Edge}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Edge)
        com.pantheon.hermes.grpc.HermesOuterClass.EdgeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Edge_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Edge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pantheon.hermes.grpc.HermesOuterClass.Edge.class, com.pantheon.hermes.grpc.HermesOuterClass.Edge.Builder.class);
      }

      // Construct using com.pantheon.hermes.grpc.HermesOuterClass.Edge.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vertexFrom_ = 0;

        vertexTo_ = 0;

        summand_ = 0F;

        multiplier_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Edge_descriptor;
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Edge getDefaultInstanceForType() {
        return com.pantheon.hermes.grpc.HermesOuterClass.Edge.getDefaultInstance();
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Edge build() {
        com.pantheon.hermes.grpc.HermesOuterClass.Edge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Edge buildPartial() {
        com.pantheon.hermes.grpc.HermesOuterClass.Edge result = new com.pantheon.hermes.grpc.HermesOuterClass.Edge(this);
        result.vertexFrom_ = vertexFrom_;
        result.vertexTo_ = vertexTo_;
        result.summand_ = summand_;
        result.multiplier_ = multiplier_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pantheon.hermes.grpc.HermesOuterClass.Edge) {
          return mergeFrom((com.pantheon.hermes.grpc.HermesOuterClass.Edge)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pantheon.hermes.grpc.HermesOuterClass.Edge other) {
        if (other == com.pantheon.hermes.grpc.HermesOuterClass.Edge.getDefaultInstance()) return this;
        if (other.getVertexFrom() != 0) {
          setVertexFrom(other.getVertexFrom());
        }
        if (other.getVertexTo() != 0) {
          setVertexTo(other.getVertexTo());
        }
        if (other.getSummand() != 0F) {
          setSummand(other.getSummand());
        }
        if (other.getMultiplier() != 0F) {
          setMultiplier(other.getMultiplier());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pantheon.hermes.grpc.HermesOuterClass.Edge parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pantheon.hermes.grpc.HermesOuterClass.Edge) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int vertexFrom_ ;
      /**
       * <code>int32 vertexFrom = 1;</code>
       */
      public int getVertexFrom() {
        return vertexFrom_;
      }
      /**
       * <code>int32 vertexFrom = 1;</code>
       */
      public Builder setVertexFrom(int value) {
        
        vertexFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 vertexFrom = 1;</code>
       */
      public Builder clearVertexFrom() {
        
        vertexFrom_ = 0;
        onChanged();
        return this;
      }

      private int vertexTo_ ;
      /**
       * <code>int32 vertexTo = 2;</code>
       */
      public int getVertexTo() {
        return vertexTo_;
      }
      /**
       * <code>int32 vertexTo = 2;</code>
       */
      public Builder setVertexTo(int value) {
        
        vertexTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 vertexTo = 2;</code>
       */
      public Builder clearVertexTo() {
        
        vertexTo_ = 0;
        onChanged();
        return this;
      }

      private float summand_ ;
      /**
       * <code>float summand = 3;</code>
       */
      public float getSummand() {
        return summand_;
      }
      /**
       * <code>float summand = 3;</code>
       */
      public Builder setSummand(float value) {
        
        summand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float summand = 3;</code>
       */
      public Builder clearSummand() {
        
        summand_ = 0F;
        onChanged();
        return this;
      }

      private float multiplier_ ;
      /**
       * <code>float multiplier = 4;</code>
       */
      public float getMultiplier() {
        return multiplier_;
      }
      /**
       * <code>float multiplier = 4;</code>
       */
      public Builder setMultiplier(float value) {
        
        multiplier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float multiplier = 4;</code>
       */
      public Builder clearMultiplier() {
        
        multiplier_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Edge)
    }

    // @@protoc_insertion_point(class_scope:Edge)
    private static final com.pantheon.hermes.grpc.HermesOuterClass.Edge DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pantheon.hermes.grpc.HermesOuterClass.Edge();
    }

    public static com.pantheon.hermes.grpc.HermesOuterClass.Edge getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Edge>
        PARSER = new com.google.protobuf.AbstractParser<Edge>() {
      @java.lang.Override
      public Edge parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Edge(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Edge> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Edge> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.pantheon.hermes.grpc.HermesOuterClass.Edge getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CycleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Cycle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 vertex = 1;</code>
     */
    java.util.List<java.lang.Integer> getVertexList();
    /**
     * <code>repeated int32 vertex = 1;</code>
     */
    int getVertexCount();
    /**
     * <code>repeated int32 vertex = 1;</code>
     */
    int getVertex(int index);

    /**
     * <code>int32 responseCode = 2;</code>
     */
    int getResponseCode();

    /**
     * <code>string responseMessage = 3;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 3;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * Protobuf type {@code Cycle}
   */
  public  static final class Cycle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Cycle)
      CycleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cycle.newBuilder() to construct.
    private Cycle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cycle() {
      vertex_ = java.util.Collections.emptyList();
      responseCode_ = 0;
      responseMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cycle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vertex_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              vertex_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                vertex_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                vertex_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {

              responseCode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vertex_ = java.util.Collections.unmodifiableList(vertex_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Cycle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Cycle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pantheon.hermes.grpc.HermesOuterClass.Cycle.class, com.pantheon.hermes.grpc.HermesOuterClass.Cycle.Builder.class);
    }

    private int bitField0_;
    public static final int VERTEX_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> vertex_;
    /**
     * <code>repeated int32 vertex = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getVertexList() {
      return vertex_;
    }
    /**
     * <code>repeated int32 vertex = 1;</code>
     */
    public int getVertexCount() {
      return vertex_.size();
    }
    /**
     * <code>repeated int32 vertex = 1;</code>
     */
    public int getVertex(int index) {
      return vertex_.get(index);
    }
    private int vertexMemoizedSerializedSize = -1;

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 2;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string responseMessage = 3;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getVertexList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(vertexMemoizedSerializedSize);
      }
      for (int i = 0; i < vertex_.size(); i++) {
        output.writeInt32NoTag(vertex_.get(i));
      }
      if (responseCode_ != 0) {
        output.writeInt32(2, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, responseMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < vertex_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(vertex_.get(i));
        }
        size += dataSize;
        if (!getVertexList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        vertexMemoizedSerializedSize = dataSize;
      }
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, responseMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pantheon.hermes.grpc.HermesOuterClass.Cycle)) {
        return super.equals(obj);
      }
      com.pantheon.hermes.grpc.HermesOuterClass.Cycle other = (com.pantheon.hermes.grpc.HermesOuterClass.Cycle) obj;

      boolean result = true;
      result = result && getVertexList()
          .equals(other.getVertexList());
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getVertexCount() > 0) {
        hash = (37 * hash) + VERTEX_FIELD_NUMBER;
        hash = (53 * hash) + getVertexList().hashCode();
      }
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pantheon.hermes.grpc.HermesOuterClass.Cycle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cycle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Cycle)
        com.pantheon.hermes.grpc.HermesOuterClass.CycleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Cycle_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Cycle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pantheon.hermes.grpc.HermesOuterClass.Cycle.class, com.pantheon.hermes.grpc.HermesOuterClass.Cycle.Builder.class);
      }

      // Construct using com.pantheon.hermes.grpc.HermesOuterClass.Cycle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vertex_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        responseCode_ = 0;

        responseMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pantheon.hermes.grpc.HermesOuterClass.internal_static_Cycle_descriptor;
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Cycle getDefaultInstanceForType() {
        return com.pantheon.hermes.grpc.HermesOuterClass.Cycle.getDefaultInstance();
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Cycle build() {
        com.pantheon.hermes.grpc.HermesOuterClass.Cycle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.pantheon.hermes.grpc.HermesOuterClass.Cycle buildPartial() {
        com.pantheon.hermes.grpc.HermesOuterClass.Cycle result = new com.pantheon.hermes.grpc.HermesOuterClass.Cycle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          vertex_ = java.util.Collections.unmodifiableList(vertex_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vertex_ = vertex_;
        result.responseCode_ = responseCode_;
        result.responseMessage_ = responseMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pantheon.hermes.grpc.HermesOuterClass.Cycle) {
          return mergeFrom((com.pantheon.hermes.grpc.HermesOuterClass.Cycle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pantheon.hermes.grpc.HermesOuterClass.Cycle other) {
        if (other == com.pantheon.hermes.grpc.HermesOuterClass.Cycle.getDefaultInstance()) return this;
        if (!other.vertex_.isEmpty()) {
          if (vertex_.isEmpty()) {
            vertex_ = other.vertex_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVertexIsMutable();
            vertex_.addAll(other.vertex_);
          }
          onChanged();
        }
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pantheon.hermes.grpc.HermesOuterClass.Cycle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pantheon.hermes.grpc.HermesOuterClass.Cycle) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> vertex_ = java.util.Collections.emptyList();
      private void ensureVertexIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vertex_ = new java.util.ArrayList<java.lang.Integer>(vertex_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 vertex = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getVertexList() {
        return java.util.Collections.unmodifiableList(vertex_);
      }
      /**
       * <code>repeated int32 vertex = 1;</code>
       */
      public int getVertexCount() {
        return vertex_.size();
      }
      /**
       * <code>repeated int32 vertex = 1;</code>
       */
      public int getVertex(int index) {
        return vertex_.get(index);
      }
      /**
       * <code>repeated int32 vertex = 1;</code>
       */
      public Builder setVertex(
          int index, int value) {
        ensureVertexIsMutable();
        vertex_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 vertex = 1;</code>
       */
      public Builder addVertex(int value) {
        ensureVertexIsMutable();
        vertex_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 vertex = 1;</code>
       */
      public Builder addAllVertex(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureVertexIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vertex_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 vertex = 1;</code>
       */
      public Builder clearVertex() {
        vertex_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 3;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 3;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 3;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 3;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Cycle)
    }

    // @@protoc_insertion_point(class_scope:Cycle)
    private static final com.pantheon.hermes.grpc.HermesOuterClass.Cycle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pantheon.hermes.grpc.HermesOuterClass.Cycle();
    }

    public static com.pantheon.hermes.grpc.HermesOuterClass.Cycle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cycle>
        PARSER = new com.google.protobuf.AbstractParser<Cycle>() {
      @java.lang.Override
      public Cycle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cycle(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cycle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cycle> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.pantheon.hermes.grpc.HermesOuterClass.Cycle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Graph_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Graph_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Edge_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Edge_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Cycle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Cycle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014hermes.proto\"\034\n\005Graph\022\023\n\004edge\030\001 \003(\0132\005." +
      "Edge\"Q\n\004Edge\022\022\n\nvertexFrom\030\001 \001(\005\022\020\n\010vert" +
      "exTo\030\002 \001(\005\022\017\n\007summand\030\003 \001(\002\022\022\n\nmultiplie" +
      "r\030\004 \001(\002\"F\n\005Cycle\022\016\n\006vertex\030\001 \003(\005\022\024\n\014resp" +
      "onseCode\030\002 \001(\005\022\027\n\017responseMessage\030\003 \001(\t2" +
      "%\n\006Hermes\022\033\n\tarbitrate\022\006.Graph\032\006.CycleB\032" +
      "\n\030com.pantheon.hermes.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Graph_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Graph_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Graph_descriptor,
        new java.lang.String[] { "Edge", });
    internal_static_Edge_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Edge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Edge_descriptor,
        new java.lang.String[] { "VertexFrom", "VertexTo", "Summand", "Multiplier", });
    internal_static_Cycle_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Cycle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Cycle_descriptor,
        new java.lang.String[] { "Vertex", "ResponseCode", "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
